# Generated by Django 6.0.4 on 2026-04-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Teatro', 'Teatro'), ('Sala de reuniones', 'Sala de reuniones'), ('Biblioteca', 'Biblioteca'), ('Laboratorio', 'Laboratorio'), ('Deportivo', 'Deportivo')], max_length=50)),
                ('descripcion', models.TextField()),
                ('capacidad', models.PositiveIntegerField()),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
