# Generated by Django 5.2.14 on 2026-06-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0004_alter_espacio_id_alter_historialreserva_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='mostrado',
            field=models.BooleanField(default=False),
        ),
    ]
