# Generated by Django 5.2.14 on 2026-06-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0005_notificacion_mostrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
